name: "NPM Install"
description: "Zero config NPM package installer with caching"
author: "umidbekk"

inputs:
  working-directory:
    required: false
    description: "The default working directory"

  cache-key:
    required: false
    description: "An explicit key for restoring and saving the cache"

runs:
  using: "node12"
  main: "dist/index.js"
