name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
      - uses: actions/checkout@v2

      - uses: ./npm/install
        with:
          cache-key: npm-${{ matrix.os }}-

      - run: yarn tsc
      - run: yarn lint
      - run: yarn build
