name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2

      - uses: ./npm/install

      - run: yarn tsc
      - run: yarn lint
      - run: yarn build

      - uses: EndBug/add-and-commit@v7
        if: ${{ failure() && github.event_name == 'pull_request' }}
