name: E2E

on:
  pull_request:
    branches:
      - main

jobs:
  npm-install-cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./npm/install
        with:
          working-directory: ./examples/cypress-npm
          cache-key: npm-install-cypress-v1-${{ github.sha }}-

      - run: npm test
        working-directory: ./examples/cypress-npm

  npm-install-cypress-yarn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./npm/install
        with:
          cache-key: yarn-install-cypress-v1-${{ github.sha }}-
          working-directory: ./examples/cypress-yarn

      - run: yarn test
        working-directory: ./examples/cypress-yarn

  prepare-node-repo-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./prepare-node-repo
        with:
          working-directory: ./examples/cypress-npm
          cache-key: prepare-node-repo-cypress-v1-${{ github.sha }}-

      - run: npm test
        working-directory: ./examples/cypress-npm

  prepare-node-repo-cypress-yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./prepare-node-repo
        with:
          working-directory: ./examples/cypress-yarn
          cache-key: prepare-node-repo-cypress-yarn-v1-${{ github.sha }}-

      - run: yarn test
        working-directory: ./examples/cypress-yarn
