name: E2E

on:
  pull_request:
    branches:
      - main

jobs:
  npm-install-cypress:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: ./npm/install
        with:
          working-directory: ./examples/cypress-npm
          cache-key: npm-install-cypress-${{ github.sha }}-

      - run: npm test
        working-directory: ./examples/cypress-npm

  npm-install-cypress-yarn:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: ./npm/install
        with:
          cache-key: yarn-install-cypress-${{ github.sha }}-
          working-directory: ./examples/cypress-yarn

      - run: yarn test
        working-directory: ./examples/cypress-yarn

  prepare-node-repo-cypress:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: ./prepare-node-repo
        with:
          node-version: ${{ matrix.node }}
          working-directory: ./examples/cypress-npm
          cache-key: prepare-node-repo-cypress-${{ github.sha }}-

      - run: npm test
        working-directory: ./examples/cypress-npm

  prepare-node-repo-cypress-yarn:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - uses: ./prepare-node-repo
        with:
          node-version: ${{ matrix.node }}
          working-directory: ./examples/cypress-yarn
          cache-key: prepare-node-repo-cypress-yarn-${{ github.sha }}-

      - run: yarn test
        working-directory: ./examples/cypress-yarn
