name: PR

on:
  pull_request:
    branches:
      - "**"

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: ./npm/install

      - run: yarn tsc
      - run: yarn lint
      - run: yarn build
      - run: git add .
      - run: git diff --quiet || exit 1
